echo -e "\e[31mPLEASE NOTE:\e[0m \e[33mYou are using a permanently-beta version of program. Be careful!\e[0m"
user=$(whoami)
echo -e "\e[1;31mALIASES:\e[0m"
echo -e "\e[33malias\e[0m \e[1;97mssvm\e[0m\e[33m='bash /home/$user/$(dirname $0)/ssv.sh'\e[0m     \e[1;97m- Main program\e[0m"
echo -e "\e[33malias\e[0m \e[1;97mssv\e[0m\e[33m='bash /home/$user/$(dirname $0)/ssv.sh c'\e[0m  \e[1;97m- Instant check\e[0m"
echo -e "\e[33malias\e[0m \e[1;97mssvk\e[0m\e[33m='bash /home/$user/$(dirname $0)/ssv.sh e'\e[0m  \e[1;97m- Gate cleaner\e[0m"
echo -e "\e[33malias\e[0m \e[1;97mssvf\e[0m\e[33m='bash /home/$user/$(dirname $0)/scenaries/fastdomcheck.sh'\e[0m \e[1;97m- Fast domain checker\e[0m"
echo -e "\e[33malias\e[0m \e[1;97mssva\e[0m\e[33m='bash /home/$user/$(dirname $0)/addkey.sh'\e[0m \e[1;97m- Add ssh-id key to the gate\e[0m"
echo -e "\e[33malias\e[0m \e[1;97mssvd\e[0m\e[33m='bash /home/$user/$(dirname $0)/checkdel.sh'\e[0m \e[1;97m- Check domain delegation.\e[0m"
echo -e "\e[33malias\e[0m \e[1;97mssvw\e[0m\e[33m='bash /home/$user/$(dirname $0)/whoismask.sh'\e[0m \e[1;97m- Check domain redelegation by using excluding mask.\e[0m"
echo -e "\e[33malias\e[0m \e[1;97mssvp\e[0m\e[33m='bash /home/$user/$(dirname $0)/portcheck.sh'\e[0m \e[1;97m- Check bind and nginx port availability.\e[0m"
echo -e "\e[33malias\e[0m \e[1;97mssvc\e[0m\e[33m='bash /home/$user/$(dirname $0)/passgen.sh'\e[0m \e[1;97m- Get passwords and hash to setup the gate.\e[0m"
echo -e "\e[33malias\e[0m \e[1;97mssvs\e[0m\e[33m'bash /home/$user/$(dirname $0)/ssl_check.sh'\e[0m \e[1;97m- Check SSL for domains.\e[0m"
echo -e "\e[33mOPTIONS: start ssvf and put domains, or use persistent file with domains. For example: ssvf domains.yml. Certainly, you can use grep for higher precision.\e[0m" 
echo -e "\e[33mKeys: ENTER (YES/CONTINUE), "+" (NO/SKIP)\e[0m"
echo -e "\e[1;96mKnown ISSUES:\e[0m"
echo -e "\e[33m - Sometimes gives a message, that a domain with a registrar's A-note is inactive."
echo -e " - Creates incorrect dom-file, if the group has active bind-services with different A-notes with equal ratio for domains, f.e. 50/50.\e[0m"
